apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: vault-external-secret
  namespace: external-secrets
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  target:
    name: example-secret # Kubernetes secret name
  data:
    - secretKey: foobar # This will be the key in kubernetes secret.
      remoteRef: # Vault information about secret
        key: app/mysecret # Path of secret
        property: foo # Key of secret in vault
