apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: vault-backend
spec:
  provider:
    vault:
      server: "http://vault-server.vault.svc.cluster.local:8200" # Указываем адрес Hashicorp Vault.
      path: "secret" # Только по этому пути может ходить ClusterSecretStore в Hashicorp Vault.
      version: "v2"
      auth:
        # AppRole аутентифицируется в Vault с помощью механизма
        # аутентификации AppRole https://www.vaultproject.io/docs/auth/approle.
        appRole:
          # Путь, по которому подключен сервер аутентификации AppRole.
          path: "approle"
          # Идентификатор роли, настроенный в серверной части проверки подлинности AppRole.
          roleId: "" # Значение берем из  вывода `terraform output role_id`.
          secretRef:
            name: "vault-secret" # Название секрета Kubernetes, содержащий секретный идентификатор AppRole.
            key: "secret-id" # Секретный идентификатор AppRole.
            namespace: external-secrets # Пространство имен, в котором вы можете найти секретный идентификатор для данной AppRole.
